import { StyleSheet } from "react-native";

export const colors = {
  freshGreen: "rgb(132, 189, 57)",
  softIvory: "rgb(242, 236, 220)",
  refinedCharcoalGray: "rgb(47, 47, 47)",
  slateBlue: "rgb(94, 127, 164)",
  elegantGold: "rgb(189, 175, 100)",
  lightGray: "rgb(201, 199, 180)",
  yellow: "rgb(245, 203, 66)",
  red: "rgb(199, 67, 50)",
};

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 5,
    backgroundColor: colors.softIvory,
  },
  secondaryContainer: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    backgroundColor: colors.softIvory,
  },
  scrollContainer: {
    padding: 20,
    alignItems: "center",
    backgroundColor: colors.softIvory,
  },
  separator: {
    height: 1,
    backgroundColor: colors.refinedCharcoalGray,
    marginVertical: 10,
  },
  titleText: {
    fontSize: 22,
    fontWeight: "600",
    color: colors.refinedCharcoalGray,
    marginBottom: 20,
    textAlign: "center",
  },
  welcomeText: {
    fontSize: 25,
    fontWeight: "600",
    color: colors.refinedCharcoalGray,
    marginBottom: 20,
    marginTop: 40,
    textAlign: "center",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  touchableText: {
    color: colors.softIvory,
    fontSize: 16,
    fontWeight: "500",
  },
  header: {
    fontSize: 24,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 20,
    color: colors.refinedCharcoalGray,
  },
  error: {
    color: "red",
    marginBottom: 20,
  },
  dashboardChart: {
    zIndex: 10,
    marginVertical: 20,
    alignItems: "center",
    backgroundColor: colors.lightGray,
    borderRadius: 12,
    padding: 15,
    shadowColor: colors.lightGray,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  touchable: {
    backgroundColor: colors.slateBlue,
    paddingVertical: 20,
    paddingHorizontal: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    shadowColor: colors.refinedCharcoalGray,
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    width: 250,
  },
  scanTouchable: {
    backgroundColor: colors.slateBlue,
    paddingVertical: 20,
    paddingHorizontal: 40,
    borderRadius: 250 / 2,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    shadowColor: colors.refinedCharcoalGray,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    width: 250,
    height: 250,
  },
  logoutTouchable: {
    backgroundColor: colors.slateBlue,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
    shadowColor: colors.refinedCharcoalGray,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    width: 250,
  },
  button: {
    marginTop: 20,
    backgroundColor: colors.slateBlue,
    borderRadius: 8,
    padding: 10,
  },
  input: {
    height: 50,
    width: 250,
    borderColor: colors.refinedCharcoalGray,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 15,
    marginBottom: 20,
    backgroundColor: colors.softIvory,
    fontSize: 16,
    color: colors.refinedCharcoalGray,
    shadowColor: colors.refinedCharcoalGray,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  pickerContainer: {
    width: 250,
    height: 50,
    marginTop: 10,
  },
  dropdown: {
    position: "absolute",
    width: 250,
    backgroundColor: colors.softIvory,
    borderRadius: 8,
  },
  guideContainer: {
    backgroundColor: colors.lightGray,
    padding: 20,
    borderRadius: 12,
    shadowColor: colors.refinedCharcoalGray,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  stepText: {
    fontSize: 18,
    color: colors.refinedCharcoalGray,
    marginBottom: 10,
  },
});
